update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release'
      print_command_output: false
    )
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store
  end
end
